### ISSUE TITLE
can shuttlecock be tracked in realtime in live match using tracknetv3 if that is possible how?

### ISSUE THREAD

**Issue by Shekharmeena28** [alenzenx/TracknetV3#7]

**Comment by alenzenx** [comment]
Real-time detection requires you to write your own program to accomplish it. It’s not provided at the moment, but it is feasible.GPU needs to be good enough, at least greater than RTX3060 12G.The most basic solution is that the GPU must be able to process 3 pictures per second from input to output, so as to avoid lag and achieve real-time detection.If your GPU can process 30 images per second from input to output, that will be the best result. However, this solution has quite high performance requirements for the GPU. If you have such a high-end GPU, Parallel processing can also be considered.
